### ISSUE TITLE
[BUG] 存在しない年の処理

### ISSUE THREAD

**Issue by a01sa01to** [kss-pc-club/discord-bot#1]
## 🤨 起こっている問題
- 2012以下の整数Xに対し、`!register X` を入力すると存在しない回が表示される
- 現在は2022年だが、2023年以降も許容されている
- 小数も許容している

## 📷 スクリーンショット

![image](https://user-images.githubusercontent.com/26807394/159305451-2a76941a-0415-46b1-9685-d16e53ffe2f3.png)
![image](https://user-images.githubusercontent.com/26807394/159305474-8e03df58-4f11-44a3-804c-95233951b746.png)
![image](https://user-images.githubusercontent.com/26807394/159305508-66c17427-f05b-41f6-baa7-dd3556b92794.png)

## 😀 期待する見せ方・挙動
- 予期せぬ入力がされた場合には、ちゃんと入力するようなメッセージを出すべき

## 👀 起こっている問題の再現手段
1. registerチャンネルに適当に打つ

## 🖥 動作環境・ブラウザ
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Ryoga-exe** [comment]
現状のコードは `parseInt()` で対応している

https://github.com/kss-pc-club/discord-bot/blob/main/src/commands/register.ts#L12
